### ISSUE TITLE
feat(ci-cd): implement comprehensive ci/cd pipeline for refactored architecture

### ISSUE THREAD

**Issue by BjornMelin** [BjornMelin/tripsage-ai#166]
## Overview
Implement comprehensive CI/CD pipeline supporting the complete refactored TripSage architecture with LangGraph agents, direct SDK integrations, Mem0 memory system, Crawl4AI web crawling, and Next.js 15 frontend.

## Background
The refactored architecture requires a modern CI/CD pipeline that supports the new technology stack and deployment patterns while ensuring quality gates, security, and performance validation across all components.

## Scope
This issue consolidates the CI/CD requirements outlined in TODO.md and coordinates with all active refactoring efforts to provide comprehensive automation for the entire stack.

## Current State
- Basic CI infrastructure exists
- Partial implementation for some components
- Quality gates need enhancement
- Security scanning needs implementation
- Performance testing needs automation

### Multi-Stage Pipeline
```yaml
# .github/workflows/main.yml
name: TripSage CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Stage 1: Code Quality & Security
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Code Quality Checks
      - name: Security Scanning
      - name: Dependency Audit
  
  # Stage 2: Backend Testing
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
      - name: Integration Tests
      - name: Performance Tests
  
  # Stage 3: Frontend Testing  
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
      - name: E2E Tests
      - name: Bundle Analysis
  
  # Stage 4: Build & Deploy
  deploy:
    needs: [quality-gates, backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Build Images
      - name: Deploy to Environment
      - name: Health Checks
```

### Phase 1: Quality Gates & Security (Week 1)

- [ ] **Code Quality Pipeline**
  - Configure ruff for Python linting and formatting
  - Set up Biome for TypeScript/JavaScript linting
  - Implement pre-commit hooks integration
  - Add type checking with mypy for Python
  - Configure TypeScript strict mode validation

- [ ] **Security Scanning**
  - Implement Bandit for Python security scanning
  - Add npm audit for JavaScript dependencies
  - Configure Snyk for vulnerability scanning
  - Set up secret scanning with GitHub Advanced Security
  - Add SAST (Static Application Security Testing)

- [ ] **Dependency Management**
  - Automated dependency updates with Dependabot
  - License compliance checking
  - Vulnerability scanning and reporting
  - Pin dependency versions for reproducible builds

### Phase 2: Backend CI Pipeline (Week 2)

- [ ] **Python/FastAPI Pipeline**
  - Test with multiple Python versions (3.12+)
  - Run comprehensive test suite with pytest
  - Generate coverage reports (90%+ requirement)
  - Integration testing with mocked services
  - Performance testing for API endpoints

- [ ] **Service Testing**
  - Test LangGraph agent workflows
  - Validate direct SDK integrations
  - Test Mem0 memory system integration
  - Validate Crawl4AI web crawling functionality
  - Test database operations with Supabase

- [ ] **API Documentation**
  - Automated OpenAPI schema generation
  - API documentation deployment
  - Contract testing validation
  - Breaking change detection

### Phase 3: Frontend CI Pipeline (Week 3)

- [ ] **Next.js 15 Testing**
  - Unit tests with Vitest and React Testing Library
  - Component testing with comprehensive coverage
  - Integration testing for API connections
  - Build optimization and bundle analysis

- [ ] **E2E Testing**
  - Playwright tests for critical user flows
  - Cross-browser compatibility testing
  - Mobile responsive testing
  - Accessibility testing (WCAG compliance)

- [ ] **Performance Testing**
  - Core Web Vitals measurement
  - Bundle size monitoring and alerts
  - Performance budget enforcement
  - Lighthouse CI integration

### Phase 4: Containerization & Deployment (Week 4)

- [ ] **Docker Optimization**
  - Multi-stage Docker builds for production
  - Separate containers for backend and frontend
  - Health check endpoints implementation
  - Container security scanning

- [ ] **Infrastructure as Code**
  - Docker Compose for local development
  - Production deployment configurations
  - Environment-specific configurations
  - Secrets management integration

### Phase 5: Environment Management (Week 5)

- [ ] **Multi-Environment Support**
  - Development environment automation
  - Staging environment with production parity
  - Production deployment with rollback capability
  - Feature branch deployments

- [ ] **Configuration Management**
  - Environment-specific configurations
  - Secret management with GitHub Secrets
  - Feature flag integration
  - Database migration automation

### Phase 6: Monitoring & Observability (Week 6)

- [ ] **Application Monitoring**
  - OpenTelemetry integration in CI/CD
  - Performance monitoring setup
  - Error tracking and alerting
  - Business metrics collection

- [ ] **Deployment Monitoring**
  - Health check validation post-deployment
  - Rollback automation on failure
  - Performance regression detection
  - User experience monitoring

### Backend Testing Pipeline
```yaml
backend-tests:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.12, 3.13]
  
  services:
    postgres:
      image: postgres:15
      env:
        POSTGRES_PASSWORD: postgres
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
    
    redis:
      image: redis:7
      options: >-
        --health-cmd "redis-cli ping"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Install dependencies
      run: uv pip sync requirements.txt
    
    - name: Run ruff linting
      run: ruff check . --output-format=github
    
    - name: Run ruff formatting
      run: ruff format . --check
    
    - name: Run type checking
      run: mypy tripsage/
    
    - name: Run tests with coverage
      run: |
        uv run pytest --cov=tripsage --cov-report=xml --cov-report=html
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        
    - name: Test LangGraph agents
      run: uv run pytest tests/agents/ -v
      
    - name: Test direct SDK integrations
      run: uv run pytest tests/services/ -v
      
    - name: Test memory system
      run: uv run pytest tests/memory/ -v
      
    - name: Performance tests
      run: uv run pytest tests/performance/ -v
```

### Frontend Testing Pipeline
```yaml
frontend-tests:
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'frontend/pnpm-lock.yaml'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: cd frontend && pnpm install --frozen-lockfile
    
    - name: Run Biome linting
      run: cd frontend && npx biome lint .
    
    - name: Run Biome formatting
      run: cd frontend && npx biome format . --write
    
    - name: Type checking
      run: cd frontend && pnpm type-check
    
    - name: Unit tests
      run: cd frontend && pnpm test --coverage
    
    - name: Build application
      run: cd frontend && pnpm build
    
    - name: Bundle analysis
      run: cd frontend && pnpm analyze
    
    - name: E2E tests
      run: cd frontend && pnpm test:e2e
    
    - name: Lighthouse CI
      run: cd frontend && pnpm lighthouse-ci
```

### Security Pipeline
```yaml
security-scan:
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v4
    
    - name: Python security scan
      run: |
        pip install bandit[toml]
        bandit -r tripsage/ -f json -o bandit-report.json
    
    - name: JavaScript security audit
      run: |
        cd frontend
        npm audit --audit-level moderate
    
    - name: Snyk security scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
    
    - name: Secret scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
```

### Backend Performance
```python
# tests/performance/test_api_performance.py
import asyncio
import time
from httpx import AsyncClient

async def test_agent_response_time():
    """Test LangGraph agent response time meets 2-5x improvement target"""
    async with AsyncClient() as client:
        start_time = time.time()
        response = await client.post("/api/v1/chat", json={
            "message": "Plan a trip to Japan",
            "user_id": "test_user"
        })
        end_time = time.time()
        
        assert response.status_code == 200
        assert (end_time - start_time) < 2.0  # 2s target

async def test_memory_search_latency():
    """Test memory search meets <100ms requirement"""
    async with AsyncClient() as client:
        start_time = time.time()
        response = await client.get("/api/v1/memory/search?query=travel+preferences")
        end_time = time.time()
        
        assert response.status_code == 200
        assert (end_time - start_time) < 0.1  # 100ms target
```

### Frontend Performance
```typescript
// tests/e2e/performance.spec.ts
import { test, expect } from '@playwright/test'

test('Core Web Vitals compliance', async ({ page }) => {
  await page.goto('/')
  
  // Measure Core Web Vitals
  const vitals = await page.evaluate(() => {
    return new Promise((resolve) => {
      new PerformanceObserver((list) => {
        const entries = list.getEntries()
        const vitals = {}
        entries.forEach((entry) => {
          if (entry.name === 'FCP') vitals.fcp = entry.value
          if (entry.name === 'LCP') vitals.lcp = entry.value
          if (entry.name === 'CLS') vitals.cls = entry.value
        })
        resolve(vitals)
      }).observe({ entryTypes: ['web-vitals'] })
    })
  })
  
  expect(vitals.fcp).toBeLessThan(1200) // 1.2s FCP target
  expect(vitals.lcp).toBeLessThan(2500) // 2.5s LCP target
  expect(vitals.cls).toBeLessThan(0.1)  // 0.1 CLS target
})
```

### Production Deployment
```yaml
deploy-production:
  if: github.ref == 'refs/heads/main'
  needs: [quality-gates, backend-tests, frontend-tests]
  runs-on: ubuntu-latest
  
  steps:
    - name: Deploy to production
      run: |
        # Deploy backend services
        docker-compose -f docker-compose.prod.yml up -d
        
        # Deploy frontend
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        
        # Run health checks
        ./scripts/health-check.sh
        
        # Update monitoring
        ./scripts/update-monitoring.sh
    
    - name: Notify deployment
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
```

### Rollback Automation
```yaml
rollback:
  runs-on: ubuntu-latest
  if: failure()
  
  steps:
    - name: Automatic rollback
      run: |
        # Rollback to previous version
        ./scripts/rollback.sh
        
        # Verify rollback success
        ./scripts/health-check.sh
        
        # Notify team
        ./scripts/notify-rollback.sh
```

### Required Checks
- [ ] Code quality (ruff, Biome) - 100% pass rate
- [ ] Security scans - No high/critical vulnerabilities
- [ ] Test coverage - 90%+ backend, 90%+ frontend
- [ ] Performance tests - All benchmarks met
- [ ] Bundle size - Under thresholds
- [ ] Accessibility - WCAG compliance

### Branch Protection Rules
```yaml
# Branch protection configuration
required_status_checks:
  strict: true
  contexts:
    - "quality-gates"
    - "backend-tests"
    - "frontend-tests"
    - "security-scan"

required_pull_request_reviews:
  required_approving_review_count: 2
  dismiss_stale_reviews: true
  require_code_owner_reviews: true

enforce_admins: true
allow_force_pushes: false
allow_deletions: false
```

### Deployment Metrics
```yaml
# Monitor deployment success
post-deploy-monitoring:
  runs-on: ubuntu-latest
  
  steps:
    - name: Check application health
      run: |
        curl -f ${{ secrets.APP_URL }}/health
        
    - name: Performance validation
      run: |
        # Check response times
        ./scripts/performance-check.sh
        
    - name: Business metrics
      run: |
        # Validate key business metrics
        ./scripts/business-metrics-check.sh
```

### Functional
- [ ] Complete CI/CD pipeline for all components
- [ ] Quality gates enforced for all changes
- [ ] Automated testing with 90%+ coverage
- [ ] Security scanning and vulnerability management
- [ ] Performance testing and validation
- [ ] Multi-environment deployment automation

### Performance
- [ ] Pipeline completion time <15 minutes
- [ ] Parallel execution optimization
- [ ] Efficient caching strategies
- [ ] Fast feedback loops for developers

### Reliability
- [ ] Rollback automation on failure
- [ ] Health checks and monitoring
- [ ] Notification systems for failures
- [ ] Disaster recovery procedures

## Timeline
**6 weeks** - Comprehensive CI/CD implementation

## Dependencies
- All refactoring initiatives (Issues #161, #159, #146, #139)
- Infrastructure setup and access
- Monitoring tools configuration
- Security tools integration

## References
- TODO.md CI/CD Pipeline Setup section
- DevOps best practices documentation
- Security requirements specification
- Performance benchmark definitions
